{% set name = "kcoreaddons" %}
{% set version = "5.79.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kcoreaddons-{{ version }}.tar.xz
  sha256: 6f221bd93be73aeec863cd7089c69e84fef76bea83a906c6cd2c853937813659

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kcoreaddons', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - qt
    - xorg-libxext

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5CoreAddons.so

about:
  home: https://api.kde.org/frameworks/kcoreaddons/html/index.html
  license: BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-GPL AND LicenseRef-KDE-Accepted-LGPL AND LicenseRef-Qt-Commercial AND MPL-1.1 AND Qt-LGPL-exception-1.1
  license_family: GPL
  license_file:
    - LICENSES/BSD-2-Clause.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-GPL.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
    - LICENSES/LicenseRef-Qt-Commercial.txt
    - LICENSES/MPL-1.1.txt
    - LICENSES/Qt-LGPL-exception-1.1.txt
  summary: Qt addon library with a collection of non-GUI utilities
  description: |
    KCoreAddons provides classes built on top of QtCore to perform various
    tasks such as manipulating mime types, autosaving files, creating backup
    files, generating random sequences, performing text manipulations such as
    macro replacement, accessing user information and many more.
  dev_url: https://cgit.kde.org/kcoreaddons.git/tree

extra:
  recipe-maintainers:
    - scopatz
