travis:
  secure:
    BINSTAR_TOKEN: RPnbh8on0KVbM+7zl9g8CbB+NlMfU+vn73JAkBeRHNS5FQBtIy8TJmf5Rt0yEiqkElVz/h3XerWjKI95Ew4caVBtwek1TTlJdqYQIwz2/XGavHhcpLHVbZu7etNck/OJUa7oDbuqkqztOv4uo4JMAk0DJe9BIqOLbezFzfWvAM3otgJc5lMEntE0FcJKkQJ9pau00eOn7ysNb+FktPidq9RWIs/MmN+91fYy2JADN88tqq329eLBoM458oMTYbyEJ2XyXd3gfxUMPB68wZfwwPFRA/rMTXRaZtOxVEygIFyPOI2JqTcstuemSA+T2H0sq6PETHIovlxml0duX/FVSClUWSdYLR2cxP0scwN+/C3hDQnGiVJLdPj4djZg3fMvUn3tR9tTeeuDPQv7hrbNffpr4fmc+b81TymFSpRc04Ph2tFE3HytAf2AplfoZV6oE5VOrS2sJEEM0kuraVADP4RE+W6lE38TzpUTiJZnecMO4hlDVh2FMt6ev9uqievG0Ww73WVr2vtVyJS+VLHmCsx/1kdYkoy40XrWAzN+qU3hp3cMrh/pf3BvRhHRIHZbrtd8n2TAaqWYg3g6nxnrLKPcAJWl2eMLa7hxhAS3AWnfLaUwcNFXXEyp9JBTNU1CfykfUg4uVHrF6eQ/VwJbBy5PExSoxr7yeKYcq6VJfRs=
conda_forge_output_validation: true
bot:
  check_solvable: True
